"""change enum to stringg

Revision ID: 2c6115d0ad23
Revises: 50a363ed4d53
Create Date: 2024-11-09 22:17:57.257557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c6115d0ad23'
down_revision = '50a363ed4d53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guns', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guns', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)

    # ### end Alembic commands ###
