"""add sales

Revision ID: d77b69e99b53
Revises: ee0cc714b70d
Create Date: 2024-11-13 16:37:50.048893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd77b69e99b53'
down_revision = 'ee0cc714b70d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sold_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guns', schema=None) as batch_op:
        batch_op.drop_column('sold_count')

    # ### end Alembic commands ###
